[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "postgresql"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn leadbridge.wsgi --bind 0.0.0.0:$PORT --log-file -"